/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package subtraction;

import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.lang.Math;

/**
 *
 * @author bzone
 */
public class Caculation_System_Kien extends javax.swing.JFrame {

    /**
     * Creates new form test
     */
    public Caculation_System_Kien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        aNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bNhap = new javax.swing.JTextField();
        calculate_button = new javax.swing.JButton();
        nhap_lai_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        tinhCong = new javax.swing.JRadioButton();
        tinhTru = new javax.swing.JRadioButton();
        tinhNhan = new javax.swing.JRadioButton();
        tinhChiaNguyen = new javax.swing.JRadioButton();
        tinhChiaDu = new javax.swing.JRadioButton();
        ketqua = new javax.swing.JLabel();
        tieuDeTinhToan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("a=");

        aNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aNhapActionPerformed(evt);
            }
        });

        jLabel3.setText("b=");

        bNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNhapActionPerformed(evt);
            }
        });

        calculate_button.setText("...");
        calculate_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_buttonActionPerformed(evt);
            }
        });

        nhap_lai_button.setText("Nhập lại");
        nhap_lai_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhap_lai_buttonActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Chọn phép tính"));

        buttonGroup1.add(tinhCong);
        tinhCong.setText("Cộng");
        tinhCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhCongActionPerformed(evt);
            }
        });

        buttonGroup1.add(tinhTru);
        tinhTru.setText("Trừ");
        tinhTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhTruActionPerformed(evt);
            }
        });

        buttonGroup1.add(tinhNhan);
        tinhNhan.setText("Nhân");
        tinhNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhNhanActionPerformed(evt);
            }
        });

        buttonGroup1.add(tinhChiaNguyen);
        tinhChiaNguyen.setText("Chia lấy nguyên");
        tinhChiaNguyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhChiaNguyenActionPerformed(evt);
            }
        });

        buttonGroup1.add(tinhChiaDu);
        tinhChiaDu.setText("Chia lấy dư");
        tinhChiaDu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhChiaDuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinhCong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinhTru, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinhNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinhChiaDu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tinhChiaNguyen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tinhCong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhTru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhNhan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhChiaNguyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinhChiaDu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ketqua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ketqua.setText("Kết quả:");

        tieuDeTinhToan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tieuDeTinhToan.setForeground(new java.awt.Color(255, 45, 45));
        tieuDeTinhToan.setText("THỰC HIỆN PHÉP TÍNH");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(bNhap, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                    .addComponent(aNhap)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(calculate_button)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nhap_lai_button, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ketqua)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(tieuDeTinhToan)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tieuDeTinhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(calculate_button)
                            .addComponent(nhap_lai_button))
                        .addGap(28, 28, 28)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ketqua)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jPanel4.getAccessibleContext().setAccessibleName("dssad");
        jPanel4.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aNhapActionPerformed

    private void bNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bNhapActionPerformed

    private void nhap_lai_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhap_lai_buttonActionPerformed
        // TODO add your handling code here:
        aNhap.setText("");
        bNhap.setText("");
    }//GEN-LAST:event_nhap_lai_buttonActionPerformed

    private void calculate_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_buttonActionPerformed
        //tính cộng
/*selectAll()
        if (aNhap.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "a không được để trống");
            aNhap.requestFocus();
        }
        else if (bNhap.getText().length() <= 0) {
            JOptionPane.showMessageDialog(null, "b không được để trống");
            bNhap.requestFocus();
        } else {
         */
        if (tinhCong.isSelected()) {
            try {
                double num1 = Double.parseDouble(aNhap.getText());
                double num2 = Double.parseDouble(bNhap.getText());
                double tong = num1 + num2;
                ketqua.setText("Kết quả: "+ String.valueOf(tong));

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Nhập dữ liệu sai. Hãy nhập lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        // tính trừ
        if (tinhTru.isSelected()) {
            try {
                double num1 = Double.parseDouble(aNhap.getText());
                double num2 = Double.parseDouble(bNhap.getText());
                double tru = num1 - num2;
                ketqua.setText("Kết quả: " + String.valueOf(tru));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Nhập dữ liệu sai. Hãy nhập lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        // tinh nhan
        if (tinhNhan.isSelected()) {
            try {
                double num1 = Double.parseDouble(aNhap.getText());
                double num2 = Double.parseDouble(bNhap.getText());
                double nhan = num1 * num2;
                ketqua.setText("Kết quả:" + String.valueOf(nhan));
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Nhập dữ liệu sai. Hãy nhập lại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_calculate_buttonActionPerformed

    private void tinhCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhCongActionPerformed
        // TODO add your handling code here:
        if (tinhCong.isSelected()) {
            tieuDeTinhToan.setText("THỰC HIỆN PHÉP CỘNG");
            calculate_button.setText("+");
        }
    }//GEN-LAST:event_tinhCongActionPerformed

    private void tinhTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhTruActionPerformed
        // TODO add your handling code here:
        if (tinhTru.isSelected()) {
            tieuDeTinhToan.setText("THỰC HIỆN PHÉP TRỪ");
            calculate_button.setText("-");
        }
    }//GEN-LAST:event_tinhTruActionPerformed

    private void tinhNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhNhanActionPerformed
        // TODO add your handling code here:
        if (tinhNhan.isSelected()) {
            tieuDeTinhToan.setText("THỰC HIỆN PHÉP NHÂN");
            calculate_button.setText("*");
        }
    }//GEN-LAST:event_tinhNhanActionPerformed

    private void tinhChiaDuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhChiaDuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinhChiaDuActionPerformed

    private void tinhChiaNguyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhChiaNguyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinhChiaNguyenActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caculation_System_Kien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caculation_System_Kien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caculation_System_Kien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caculation_System_Kien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caculation_System_Kien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aNhap;
    private javax.swing.JTextField bNhap;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton calculate_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel ketqua;
    private javax.swing.JButton nhap_lai_button;
    private javax.swing.JLabel tieuDeTinhToan;
    private javax.swing.JRadioButton tinhChiaDu;
    private javax.swing.JRadioButton tinhChiaNguyen;
    private javax.swing.JRadioButton tinhCong;
    private javax.swing.JRadioButton tinhNhan;
    private javax.swing.JRadioButton tinhTru;
    // End of variables declaration//GEN-END:variables
}
